# Generated by Django 3.0.6 on 2020-09-21 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('status', models.CharField(choices=[('empty', 'EMPTY'), ('booked', 'BOOKED')], max_length=32)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='parking.ParkingType')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in progress', 'IN_PROGRESS'), ('completed', 'COMPLETED')], max_length=32)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.Place')),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.Transaction')),
                ('vehicle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.Vehicle')),
            ],
        ),
    ]
