# Generated by Django 3.0.6 on 2020-09-21 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 21, 11, 17, 23, 403670)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingtype',
            name='pricing',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('in progress', 'IN_PROGRESS'), ('completed', 'COMPLETED')], default='in progress', max_length=32),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('empty', 'EMPTY'), ('booked', 'BOOKED')], default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
