# Generated by Django 3.0.6 on 2020-09-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20200921_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Place'),
        ),
    ]
