# Generated by Django 3.0.6 on 2020-09-01 16:03

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('updated_on', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('mrp', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('updated_on', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
