# Generated by Django 3.0.6 on 2020-09-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200901_1902'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_seller',
            field=models.ManyToManyField(related_name='actual_product', through='product.ProductSeller', to='user.Seller'),
        ),
        migrations.AddField(
            model_name='productseller',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productseller',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='user.Seller'),
            preserve_default=False,
        ),
    ]
