# Generated by Django 3.0.6 on 2020-09-02 09:13

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200901_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('updated_on', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('details', models.TextField(blank=True, null=True)),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('updated_on', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('sub', models.CharField(blank=True, max_length=256)),
                ('a', models.ManyToManyField(related_name='b', to='product.A')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
