# Generated by Django 3.0.6 on 2020-09-01 16:03

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_customer_seller'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('updated_on', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('payment_not_confirmed', 'PAYMENT_NOT_CONFIRMED'), ('payment_failed', 'PAYMENT_FAILED'), ('order_confirm', 'ORDER_CONFIRM'), ('packed', 'PACKED'), ('shipped', 'SHIPPED'), ('out_for_delivery', 'OUT_FOR_DELIVERY'), ('delivered', 'DELIVERED')], default='payment_not_confirmed', max_length=128)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='user.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='product.Product')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_item', to='user.Seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
